travis:
  secure:
    BINSTAR_TOKEN: G0/jSn5kebSX0XID8gu16E5GJFPBjGicy1SlHMez+RkqHKJVApigkRLRbEu0dtfb4BxjigHngDPy2YJpAfHFtBTZSFMNZTvOKGHIsvouhWdmfIa0JuYJAAGZJCMTZlRxhMlDQMeX7B056MqMdpUQ/DEVZHiWTGj+0iAcV99Ut8FYm4FhgVXOUOVkxoVH3UVZc6YT8wnVPWxy5eLqkUHSX0ULd/gj8+XDUlHybzowT+q0+USnCEkwqQTsKt/OmnmHMVDpkZWNPQ63ngP5us4dJti1Op0AoOaS+/S15tEz18YhJvhAX3DyeTZ7UUQRUXWmyb6yMMfkVWMic35tupy9aFxuBzGGW4AKxIIyIDGP+UyKjQpTcHa41EU8Th6Gr0VWc1102jnDfoLgcMaQ2NshyGMCziQLT1uj5ELFiywUX5JepdbmEQwsS8x7A4M6t2tQcyFdQfqOeXmy/xk7jfp0Qy5LYJMo1p4RsZA80buwKrVlHkTPDnFBqUcxIzUx1Ls3ZRbgmvrFVXJ7pQhtI4iXuJeta2QAjN9CnegfGUt3r4Gr5dOdhcdkHFkaYBHM95z8J5A0JiuB3YzeE5EQM2NTYnpTDWsddAp1X+Ncy/AG4wDq2K7q9/ud6fzeUEsTvzqjLz9q/5sguePrmwUJEs4iicj55iAwVYRR//sQDcUrcMY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
